/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.reports.kings;

import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.reports.ReportEditorCreator;

import java.awt.*;
import java.util.Arrays;

/**
 * @author zho
 */
public class JParamsDebtCash extends javax.swing.JPanel implements ReportEditorCreator {

    /**
     * Creates new form JParamDebtCash
     */
    public JParamsDebtCash() {
        initComponents();

        initComponents();

        lblDebtCash.setText("BON / TUNAI");

        String[] selectedValue = {"bon", "tunai"};

        ComboBoxValModel m_debtCash = new ComboBoxValModel(Arrays.asList(selectedValue));
        comboDebtCash.setModel(m_debtCash);

        comboDebtCash.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDebtCash = new javax.swing.JLabel();
        comboDebtCash = new javax.swing.JComboBox<>();

        lblDebtCash.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDebtCash.setText(AppLocal.getIntString("label.StartDate")); // NOI18N
        lblDebtCash.setPreferredSize(new java.awt.Dimension(110, 30));

        comboDebtCash.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboDebtCash.setPreferredSize(new java.awt.Dimension(160, 30));

        lblDebtCash.setText("jLabel1");
        lblDebtCash.setName(""); // NOI18N

        comboDebtCash.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"bon", "tunai"}));
        comboDebtCash.setName("comboDebtCash"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDebtCash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboDebtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDebtCash)
                                        .addComponent(comboDebtCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblDebtCash.getAccessibleContext().setAccessibleName("");
        comboDebtCash.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboDebtCash;
    private javax.swing.JLabel lblDebtCash;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init(AppView arg0) {
        //
    }

    @Override
    public void activate() throws BasicException {
        //
    }

    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public Object createValue() throws BasicException {
        return new Object[]{
                comboDebtCash.getSelectedItem() == null ? QBFCompareEnum.COMP_NONE : QBFCompareEnum.COMP_EQUALS, comboDebtCash.getSelectedItem()
        };
    }

    @Override
    public SerializerWrite getSerializerWrite() {
        return new SerializerWriteBasic(new Datas[]{Datas.OBJECT, Datas.STRING});
    }
}
