report = new com.openbravo.pos.reports.kings.KingsPanelReportBean();

report.setTitleKey("JWS.Title.TokoBarangBonTunai");
report.setReport("/com/openbravo/reports/toko_barang_bontunai");
report.setResourceBundle("com/openbravo/reports/sales_messages");

report.addParameter("tgl_transaksi");
report.addParameter("tgl_transaksi");

paramdates = new com.openbravo.pos.reports.kings.JParamsDate();
paramdates.setDate(com.openbravo.beans.DateUtils.getToday());
report.addQBFFilter(paramdates);

report;
